language: python
python:
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:ubuntugis/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-dev.txt"
    - "pip install pytest"
    - "pip install -e ."
script:
    - py.test
